
export type LabTest = {
    test: string;
    charge: number;
};

export const labTests: LabTest[] = [
    { test: "CBC", charge: 600 },
    { test: "TLC", charge: 100 },
    { test: "DLC", charge: 100 },
    { test: "AEC", charge: 300 },
    { test: "Hb", charge: 150 },
    { test: "ESR", charge: 150 },
    { test: "FBS/RBS/PBS", charge: 200 },
    { test: "RBC", charge: 100 },
    { test: "Platelets", charge: 200 },
    { test: "PCV", charge: 100 },
    { test: "MCV", charge: 100 },
    { test: "MCH", charge: 100 },
    { test: "MCHC", charge: 100 },
    { test: "RBC morphology", charge: 200 },
    { test: "Bleeding Time(BT)", charge: 100 },
    { test: "Clotting Time(CT)", charge: 100 },
    { test: "Prothrombin Time (PT/INR)", charge: 400 },
    { test: "Blood grouping", charge: 100 },
    { test: "PS for MP", charge: 450 },
    { test: "PS for Cytology", charge: 450 },
    { test: "PS for MF", charge: 250 },
    { test: "Reticulocyte Count", charge: 250 },
    { test: "Absolute Eosinophil Count (AEC)", charge: 250 },
    { test: "Urine R/M", charge: 150 },
    { test: "24 hour protein", charge: 300 },
    { test: "Triglyride", charge: 400 },
    { test: "Vitamin D", charge: 3100 },
    { test: "Stool H.pylori Ag", charge: 1200 },
    { test: "Stool R/M", charge: 150 },
    { test: "Stool RS", charge: 150 },
    { test: "Stool OBT (Occult Blood Test)", charge: 100 },
    { test: "Widal test", charge: 500 },
    { test: "ASO titre", charge: 300 },
    { test: "Typhoid IGG", charge: 800 },
    { test: "Typhoid", charge: 1200 },
    { test: "Mantoux test", charge: 200 },
    { test: "RK-39 (KA)", charge: 700 },
    { test: "Optimal test (MP)", charge: 450 },
    { test: "CRP", charge: 400 },
    { test: "RA Factor", charge: 400 },
    { test: "S-Aldehyde test", charge: 200 },
    { test: "Gram’s staining", charge: 200 },
    { test: "Sputum for AFB (2 sample)", charge: 250 },
    { test: "KOH mount (Fungus)", charge: 250 },
    { test: "Semen Analysis", charge: 400 },
    { test: "Pleural Fluid R/M", charge: 400 },
    { test: "Biochemistry", charge: 250 },
    { test: "Staining", charge: 250 },
    { test: "(Culture and sensitivity)", charge: 450 },
    { test: "Pus C/S", charge: 500 },
    { test: "Urine C/S", charge: 400 },
    { test: "Throat swab C/S", charge: 500 },
    { test: "Urine for Ketone bodies (Acetone)", charge: 250 },
    { test: "Urine Pregnancy Test (UPT)", charge: 150 },
    { test: "RBC in Urine", charge: 100 },
    { test: "Urea", charge: 250 },
    { test: "Creatinine", charge: 300 },
    { test: "Sodium (Na+)", charge: 400 },
    { test: "Potassium (k+)", charge: 400 },
    { test: "Calcium( ca++)", charge: 600 },
    { test: "Uric Acid", charge: 300 },
    { test: "Amylase", charge: 700 },
    { test: "CK-MB", charge: 1200 },
    { test: "Troponin-I", charge: 850 },
    { test: "Phosphorus", charge: 650 },
    { test: "RBS", charge: 100 },
    { test: "Fasting BSL, PP BSL", charge: 100 },
    { test: "LFT (Liver Function Test)", charge: 1200 },
    { test: "Total Bilirubim (T- Bil)", charge: 250 },
    { test: "Direct Bilirubim (D- Bill)", charge: 250 },
    { test: "SGOT(Aspartate Transaspatase) (AST)", charge: 250 },
    { test: "SGOT (Alarine Traus amunase) ALT", charge: 250 },
    { test: "Alkaline Phosphate (ALP)", charge: 150 },
    { test: "Albumin", charge: 250 },
    { test: "Total protein", charge: 250 },
    { test: "Lipid profile", charge: 1000 },
    { test: "Total cholesterol", charge: 300 },
    { test: "LDL Cholesterol", charge: 500 },
    { test: "LDL choles trol", charge: 500 },
    { test: "Typhoid IGG/IGM", charge: 800 },
    { test: "Other swab C/S", charge: 400 },
    { test: "TPHA (Syphilis)", charge: 450 },
    { test: "VDRL", charge: 350 },
    { test: "HIV", charge: 500 },
    { test: "TFT", charge: 1400 },
    { test: "T3", charge: 500 },
    { test: "T4", charge: 500 },
    { test: "TSH", charge: 800 },
    { test: "LH", charge: 1500 },
    { test: "FSH", charge: 1500 },
    { test: "Prolactin", charge: 1500 },
    { test: "Micro albumin", charge: 1000 },
    { test: "HbAlc (sugar)", charge: 1350 },
    { test: "RFT", charge: 1200 },
    { test: "PH", charge: 150 },
    { test: "Chloride", charge: 400 },
    { test: "HEV (CI)", charge: 1600 },
    { test: "HAV", charge: 1600 },
    { test: "Iron profile", charge: 3000 },
    { test: "TIBC ferritine", charge: 800 },
    { test: "Lipase", charge: 1700 },
    { test: "ABG", charge: 3500 },
    { test: "FIFT", charge: 1600 },
    { test: "H.Pylori", charge: 1300 },
    { test: "Mg+ (Magnesium)", charge: 1800 },
    { test: "Blood C/S", charge: 550 },
];
